export const softwareData = [
    {
        id: 1,
        name: "Firefox",
        version: "120.0",
        category: "網頁瀏覽器",
        license: "Mozilla Public License",
        description: "Mozilla Firefox 是一個自由及開放原始碼的網頁瀏覽器，由 Mozilla 基金會及其子公司 Mozilla 公司開發。",
        icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Firefox_logo%2C_2019.svg/1200px-Firefox_logo%2C_2019.svg.png",
        video: "https://www.youtube.com/embed/example1",
        tags: ["瀏覽器", "開源", "跨平台"],
        date: "2023-12-01",
        stars: 15000,
        forks: 2000,
        downloads: 5000000
    },
    {
        id: 2,
        name: "Ubuntu",
        version: "22.04 LTS",
        category: "作業系統",
        license: "GNU GPL",
        description: "Ubuntu 是一個以桌面應用為主的 Linux 作業系統，基於 Debian GNU/Linux。",
        icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/UbuntuCoF.svg/1200px-UbuntuCoF.svg.png",
        video: "https://www.youtube.com/embed/example2",
        tags: ["Linux", "作業系統", "伺服器"],
        date: "2022-04-21",
        stars: 25000,
        forks: 5000,
        downloads: 10000000
    },
    {
        id: 3,
        name: "LibreOffice",
        version: "7.6",
        category: "辦公室軟體",
        license: "Mozilla Public License",
        description: "LibreOffice 是一個功能強大的辦公套件，包含文書處理、試算表、簡報、繪圖、資料庫和公式編輯等功能。",
        icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/LibreOffice_logo.svg/1200px-LibreOffice_logo.svg.png",
        video: "https://www.youtube.com/embed/example3",
        tags: ["辦公", "文書處理", "試算表"],
        date: "2023-08-14",
        stars: 18000,
        forks: 3000,
        downloads: 8000000
    },
    {
        id: 4,
        name: "GIMP",
        version: "2.10.34",
        category: "圖像編輯器",
        license: "GNU GPL",
        description: "GIMP 是一個跨平台的圖像編輯軟體，提供專業級的圖像處理功能。",
        icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/The_GIMP_icon_-_gnome.svg/1200px-The_GIMP_icon_-_gnome.svg.png",
        video: "https://www.youtube.com/embed/example4",
        tags: ["圖像編輯", "照片處理", "設計"],
        date: "2023-11-20",
        stars: 12000,
        forks: 1500,
        downloads: 6000000
    },
    {
        id: 5,
        name: "Git",
        version: "2.42.0",
        category: "版本控制",
        license: "GNU GPL",
        description: "Git 是一個分散式版本控制系統，用於追蹤原始碼的變更。",
        icon: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
        video: "https://www.youtube.com/embed/example5",
        tags: ["版本控制", "程式開發", "協作"],
        date: "2023-08-30",
        stars: 45000,
        forks: 8000,
        downloads: 15000000
    },
    {
        id: 6,
        name: "VS Code",
        version: "1.85.0",
        category: "程式設計工具",
        license: "MIT",
        description: "Visual Studio Code 是一個由 Microsoft 開發的跨平台程式碼編輯器。",
        icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/1200px-Visual_Studio_Code_1.35_icon.svg.png",
        video: "https://www.youtube.com/embed/example6",
        tags: ["程式編輯器", "IDE", "開發工具"],
        date: "2023-12-05",
        stars: 150000,
        forks: 25000,
        downloads: 30000000
    },
    {
        id: 7,
        name: "MySQL",
        version: "8.0.35",
        category: "資料庫",
        license: "GNU GPL",
        description: "MySQL 是一個開源的關聯式資料庫管理系統，廣泛用於網站應用程式。",
        icon: "https://www.mysql.com/common/logos/logo-mysql-170x115.png",
        video: "https://www.youtube.com/embed/example7",
        tags: ["資料庫", "SQL", "伺服器"],
        date: "2023-10-25",
        stars: 8000,
        forks: 1200,
        downloads: 20000000
    },
    {
        id: 8,
        name: "VLC",
        version: "3.0.18",
        category: "媒體播放器",
        license: "GNU GPL",
        description: "VLC 媒體播放器是一個跨平台的多媒體播放器，支援多種音頻和視頻格式。",
        icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/VLC_Icon.svg/1200px-VLC_Icon.svg.png",
        video: "https://www.youtube.com/embed/example8",
        tags: ["媒體播放", "視頻", "音頻"],
        date: "2023-11-15",
        stars: 20000,
        forks: 3000,
        downloads: 25000000
    },
    {
        id: 9,
        name: "FileZilla",
        version: "3.66.1",
        category: "檔案管理",
        license: "GNU GPL",
        description: "FileZilla 是一個免費的 FTP 客戶端軟體，用於檔案傳輸。",
        icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/FileZilla_logo.svg/1200px-FileZilla_logo.svg.png",
        video: "https://www.youtube.com/embed/example9",
        tags: ["FTP", "檔案傳輸", "伺服器"],
        date: "2023-11-28",
        stars: 5000,
        forks: 800,
        downloads: 15000000
    },
    {
        id: 10,
        name: "Apache",
        version: "2.4.58",
        category: "網頁伺服器",
        license: "Apache License",
        description: "Apache HTTP Server 是一個開源的網頁伺服器軟體，廣泛用於網站託管。",
        icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Apache_HTTP_server_logo_%282016%29.svg/1200px-Apache_HTTP_server_logo_%282016%29.svg.png",
        video: "https://www.youtube.com/embed/example10",
        tags: ["網頁伺服器", "HTTP", "網站"],
        date: "2023-10-17",
        stars: 3000,
        forks: 500,
        downloads: 10000000
    }
]; 